<?php


namespace App\Models;


use Faker\Provider\Uuid;
use Illuminate\Database\Eloquent\Model;

abstract  class TM extends Model
{
    public $incrementing = false;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model){
            if(empty($model->id)){
                $model->id = str_replace('-','', Uuid::uuid());
            }
        });
    }

}